### ISSUE TITLE
Cannot get hedron_compile_commands to run after setup

### ISSUE THREAD

**Issue by Spiritousse** [hedronvision/bazel-compile-commands-extractor#107]
Hi, 

I am (very) new to bazel, and this project immediately stood out as a must have for me, as I am starting to work on a big codebase. 
I have been trying to make the _hedron_compile_commands_ tool work for the past few days without success.
I don't know if this question is relevant, or if the issue is even linked to the tool at all. Feel free to discard this issue in that case 😃 

Here is the configuration I setup in the WORKSPACE
```
http_archive(
    name = "hedron_compile_commands",
    url = "https://github.com/hedronvision/bazel-compile-commands-extractor/archive/abdd06e05c7949721dba4bf1ae465bde16b9d3e1.tar.gz",
    strip_prefix = "bazel-compile-commands-extractor-abdd06e05c7949721dba4bf1ae465bde16b9d3e1",
)
```

And here is the output when running the command (removed some paths for privacy)

> bazel run @hedron_compile_commands//:refresh_all
> WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
> (15:04:52) INFO: Invocation ID: 4e519e7f-7487-4e7a-9ffc-9ab5579274c2
> (15:04:52) INFO: Current date is 2023-03-01
> (15:04:52) Loading:
> (15:04:52) Loading: 0 packages loaded
> (15:04:52) Analyzing: target @hedron_compile_commands//:refresh_all (0 packages loaded, 0 targets configured)
> (15:04:52) INFO: Analyzed target @hedron_compile_commands//:refresh_all (0 packages loaded, 0 targets configured).
> (15:04:52) INFO: Found 1 target...
> (15:04:52) [1 / 12] [Prepa] BazelWorkspaceStatusAction stable-status.txt
> (15:04:53) ERROR: C:/------------/dahbz3qe/external/bazel_tools/src/main/cpp/util/BUILD:95:11: Linking external/bazel_tools/src/main/cpp/util/libport.a [for host] failed: (Exit -1): false failed: error executing command \bin\false @bazel-out/host/bin/external/bazel_tools/src/main/cpp/util/libport.a-2.params
> Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\------------\dahbz3qe\execroot\bsw\bin\false" @bazel-out/host/bin/external/bazel_tools/src/main/cpp/util/libport.a-2.params): The system cannot find the file specified.
>  (error: 2)
> (15:04:54) [10 / 34] Compiling src/main/cpp/util/path_windows.cc [for host]; 1s local, remote-cache ... (18 actions running)
> Target @hedron_compile_commands//:refresh_all failed to build

This is executed on Windows, Cygwin 3.3.2.

**Comment by cpsauer** [comment]
Hey Simon! We're honored to be on your immediate must-have list. Thanks for your interest in the tool and for writing in. In the future, definitely don't struggle for days with my tools! Just ask for help.

I'm afraid though, that that looks like a general Bazel+Windows issue around Bazel compiling some of its internal tooling. I don't do much dev on Windows at the moment--though I have tested this tool on Windows and haven't run into this--so I'm afraid I don't have the solution in mental cache. I'm really not sure why it's trying to execute false...but that seems like some kind of error case even if it did find it.

Anyway, sorry to not be the source of the (problem and) answer--so I'm going to close if that's okay. Good luck! Cheering for you as you start your Bazel adventure. Looks, at least, like you might be part of a sophisticated bazel-using operation that might have guidance? I see remote-cache in that command :) When you do figure it out, might be worth posting back here, just in case people come in via google.

Cheers,
Chris

**Comment by Spiritousse** [comment]
Hi Chris,
Thanks a lot for taking the time to answer. I will dig in that issue on my side, and I'll make sure to update this post if I find anything interesting.
This is indeed part of a quite complicated build toolchain, I think I can get some people involved with more experience than me using Bazel.

Thank you for the effort you put on this project.

**Comment by cpsauer** [comment]
You're very welcome--and thank you. Good luck!
