### ISSUE TITLE
Duplicate /TP flags cause clangd note

### ISSUE THREAD

**Issue by peakschris** [hedronvision/bazel-compile-commands-extractor#115]
I'm getting this note in clangd:

![image](https://user-images.githubusercontent.com/77508021/227816029-a163f0e9-00b6-4fa2-8d8e-1b5dd59c423a.png)

Because we specify /TP for all files in our copts, and the extractor is also adding /TP in this code (our files are named .cxx and .hxx):

https://github.com/hedronvision/bazel-compile-commands-extractor/blob/bbd6a143199d91d1ec7777545ef6dc115785cdfb/refresh.template.py#L631

Thanks!

**Comment by cpsauer** [comment]
Yup. Sorry. [You can probably see the bug right above.]

Just pushed a commit (backlinked above) that should fix. Could you confirm and close if so?

**Comment by peakschris** [comment]
It works great now, thank you so much 👍
