### ISSUE TITLE
SyntaxError when running refresh_all.

### ISSUE THREAD

**Issue by headhunter45** [hedronvision/bazel-compile-commands-extractor#119]
I'm getting this error when trying to run `bazelisk run @hedron_compile_commands//:refresh_all` on a codeanywhere.com container. It's working fine on windows with msvc and macos with llvm. The container was using python2.7 by default so I relinked python to the python3 binary, but I still got the same error. Unfortunately I don't know enough python to figure out what's going wrong.
```bash
abox@cpp-tiny-test:~/workspace/TinyTest$ bazelisk run @hedron_compile_commands//:refresh_all
INFO: Analyzed target @hedron_compile_commands//:refresh_all (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @hedron_compile_commands//:refresh_all up-to-date:
  bazel-bin/external/hedron_compile_commands/refresh_all.py
  bazel-bin/external/hedron_compile_commands/refresh_all
INFO: Elapsed time: 12.318s, Critical Path: 0.08s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/external/hedron_compile_commands/refresh_all
  File "/home/cabox/.cache/bazel/_bazel_cabox/3249da0c72f2dda2d8194d09f1ee1f65/execroot/__main__/bazel-out/k8-fastbuild/bin/external/hedron_compile_commands/refresh_all.runfiles/hedron_compile_commands/refresh_all.py", line 351
    return subprocess.run([command[0], f'@{path}'], **kwargs)
                                                ^
SyntaxError: invalid syntax
```

**Comment by cpsauer** [comment]
Hey, @headhunter45! Thanks for your interest in this tool and for writing in.

This still really looks like Bazel is trying to run the script with Python 2 to me--to my knowledge that's what causes an error like that (crossref: #95). I wish there were an easy way to give a better error message, like we do for old versions of python 3, but I couldn't quickly find one.

In your shoes I think I'd next try running a quick py_binary under bazel whose file contents are something like:
```python
import sys
print (sys.version_info)
```
and use that to debug/check that bazel is finding a modern version of python. Does that work for you?

Cheers,
Chris

**Comment by cpsauer** [comment]
[I'm going to close this down, since it's been a little bit, and this really looks like a Bazel-getting-python-2 issue, which I don't think I have much comparative advantage in. That said, please reply if you want more help and I'll open it right back up. Conversely, if you figure it out, I'd *really* appreciate your writing back in! It'll be super valuable to help the next person walking the same road as you.]

**Comment by headhunter45** [comment]
Sorry it took me so long to reply. Here is the output from that program. It looks like my python version is too old.
Oh, wow the default container is seriously out of date. It's Ubuntu 16.04 LTS. Go ahead and leave this closed. It looks like none of their containers will work. If I manage to get it to work I'll post instructions here.
```
cabox@cpp-tiny-test:~/workspace/pytest$ bazelisk run //:pytest
2023/05/12 20:46:46 Downloading https://releases.bazel.build/6.2.0/release/bazel-6.2.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:pytest (39 packages loaded, 295 targets configured).
INFO: Found 1 target...
Target //:pytest up-to-date:
  bazel-bin/pytest
INFO: Elapsed time: 11.546s, Critical Path: 0.17s
INFO: 5 processes: 5 internal.
INFO: Build completed successfully, 5 total actions
INFO: Running command line: bazel-bin/pytest
sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
cabox@cpp-tiny-test:~/workspace/pytest$ 
```

**Comment by cpsauer** [comment]
That's ok. Thanks for getting back!

It is (old) python 3, though, which makes that error super unexpected, since I'd think we'd have failed with the version check at the top :/

If you still have easy access to the container, could I ask you to investigate a little bit more? Do format strings work in there? As an example, you could append the following to test
```
path = 'test'
print(f'@{path}')
```
Any other ideas? I'm just bothered that we don't know what's going on. I don't want problems to survive that might bother you and others, but it's hard to know what this one is from a distance.

**Comment by cpsauer** [comment]
Oh, shoot. I'm wrong. Formatted string literals were introduced in python 3.6...meaning that we're going to get this error for all versions of python below our minimum.

**Comment by cpsauer** [comment]
If anyone else lands here through search: Please update your python if you can!
(I'm trying to think if there's a way to have a better error message...)

**Comment by cpsauer** [comment]
Just pushed some code to make these error messages much more robust (backlinked above). Would *love* it if you'd give it a quick test, @headhunter45, both with 3.5 and with 2.7, if you still have that container.

More generally, I think this is a python rough-edge that bazel could easily make a lot better. See https://github.com/bazelbuild/bazel/issues/18389, also backlinked above. Would love your support over there, if you're willing.

Thanks again for reporting and for your patience in working through my being wrong--that way no one ever has to be confused by this again.
