### ISSUE TITLE
Trying to put a symlink as a target

### ISSUE THREAD

**Issue by benmaia** [hedronvision/bazel-compile-commands-extractor#124]
So I have this layout:

```
|~
|- projects
         |-- application
                 |-- BUILD
                 |-- WORKSPACE
                 |-- bazel-out -> /home/~/.cache/bazel/execroot/application/bazel-out
                 |-- external -> bazel-out/../../../external
                          |-- lib
|
|-.cache
       |-- bazel
              |-- external
                        |-- lib

```

Where I'm trying to add lib inside .cache folder to the target inside BUILD in application.

The command I'm using to build that lib inside the application folder is:

`bazel build --symlink_prefix=/home/~/.cache/bazel/external/lib:all`

That doesn't have a target, it's all in the flag... But if I put it like this in targets:

`   "": "--symlink_prefix=/home/~/.cache/bazel/external/lib:all" `

It is not working because I don't have a target, any tips?

Also, I'm getting problems with the _mm_getcrs, even tho that lib it's getting compiled.

**Comment by cpsauer** [comment]
Hey, Bernardo! Great to meet you. Thanks for checking out this tool :)

I wish it weren't so, but there's something I'm not understanding about your question. Don't all `bazel build`s need to specify a target--and doesn't `--symlink_prefix` take a path fragment rather than a target?

Cheers,
Chris

**Comment by benmaia** [comment]
Hey!!

The symlink it selft take a target as well, as you can see in the end, I have to choose which target I want to run. 

`bazel build --symlink_prefix=/home/~/.cache/bazel/external/lib:all` with just this command, I can build that lib, inside my application folder. but If I try:
`bazel build //external/lib:all --symlink_prefix=/home/~/.cache/bazel/external/lib:all` it gives me an error, again, because, external is a symlink to a lib outside the WORKSPACE, and it just gives me an error.

**Comment by cpsauer** [comment]
Whoa! Huh. I can't say I've ever seen it used that way. Just to make sure I'm not missing something, we're talking about [this one, intended to add a prefix to the convenience symlinks like, bazel-testlogs, bazel-bin, etc?](https://bazel.build/reference/command-line-reference#flag--symlink_prefix) This looks like it's also effecting your output base and stuff.

Would it work to pull in the library via a workspace rule? If it's on your filesystem, then perhaps `local_repository`? I think that's the canonical way to do this kind of thing. Then you'd have a normal target to build and specify: \@{workspace_name}//:lib

**Comment by benmaia** [comment]
Yes I saw this option as well "@{workspace_name}//:lib" and still didn't work, so I had like:

` "@lib:all": "--symlink_prefix=/home/~/.cache/bazel/external/lib:all"`

Also another thing I'm noticing I'm not getting on the compile commands, is the xmmintrin.h it's coming with some _mm_getcsr linkage problem, mas that's a more deep topic ahahah

**Comment by cpsauer** [comment]
Hmm, `@lib//:all`, you mean?

I'd like to help here, but I'm not sure I have comparative advantage on these--at least not without a better understanding of what's going on with this use of symlink prefix.

**Comment by cpsauer** [comment]
Hey Bernardo, I'm going to close this one down, since I haven't heard from you in a while. But if there are still ways I can help you where I have comparative advantage--or things you think I should learn--please let me know and we can reopen.
