### ISSUE TITLE
running refresh_compile_commands function replaced all my files in bazel-bin

### ISSUE THREAD

**Issue by Jiyangson** [hedronvision/bazel-compile-commands-extractor#126]
I have successfully generated compile_commands.json. Thanks for the useful tool!
But I have a problem here. After I run bazel build for my project, it will generate some useful files in bazel-bin. Then when I run `bazel run :refresh_compile_commands` with all the same flags, it will replace all the files in the bazel-bin folder. 
Can I change the  output location of refresh_compile_commands function? I have tried --symlink_prefix but it didn't work. Thanks!
![image](https://github.com/hedronvision/bazel-compile-commands-extractor/assets/31755447/c270cf40-146a-4294-af8e-05ec5b441ffa)

**Comment by cpsauer** [comment]
Hey @Jiyangson! Thanks for your interest in the tool and kind words. Heading to bed here so I'll have to keep this pretty short.

I think bazel-bin just shows the results of the last build so building this tool will relink it as you're seeing. But the results of your prior build should still be in a subdirectory of bazel-out. 

Or you can just rerun your prior build, and it should hit cache and restore Bazel bin to the results. Does that work for you?

Cheers,
Chris

**Comment by Jiyangson** [comment]
OK I think I can rerun bazel build if there is no other way to change the location of the output. Thanks a lot.

**Comment by cpsauer** [comment]
Not that I know of, unfortunately. You're very welcome. Good luck!
