### ISSUE TITLE
external symlink breaking python vscode extensions

### ISSUE THREAD

**Issue by HaberR** [hedronvision/bazel-compile-commands-extractor#149]
Hello,

This project continues to be very helpful for myself and other members of my team. Unfortunately we've noticed recently that the `external` symlink that this tool configures no longer seems to be compatible with the other vscode extensions we use (`ms-python.vscode-pylance`, `ms-python.python`). In particular, when that symlink exists, none of the python syntax highlighting or autocomplete works anymore (this is the case for later versions of the python extensions. It seems that in prior versions, from around 5 months ago the two are compatible).

**Comment by cpsauer** [comment]
Great to hear from you again, Rafael. Delighted to hear it's been of value--and sorry to hear about the clash.

We shouldn't have changed anything here that would exacerbate things, I don't think. Any idea what's breaking in those plugins? Would you be down to report the issue to them, cc me? Not to toss it over to them too much, but I feel like they should be able to handle, and our options re external are pretty limited by the structure of Bazel.

**Comment by HaberR** [comment]
Yes so there is a pretty easy resolution which is just to add `exterrnal` to the `exclude` list in  `pyrightconfig.json`. It seems we already have `bazel-bin` in there among other things, guess we just needed one more. Going to close this ticket, thanks for the response!

**Comment by cpsauer** [comment]
Sweet! Thanks for documenting the workaround for others.

Might it be still worth filing with the tool/extensions? They probably want to be able to handle stuff common build systems might throw at them. Plus maybe people would have python code in there that they'd want completion based on?

**Comment by HaberR** [comment]
They actually do have a fairly comprehensive message about this already with a suggested mitigation, so I'm not sure there's much value in opening a new ticket with them:
```
2024-01-03 13:26:58.046 [info] [Error - 1:26:58 PM] (173330) Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.
```
