### ISSUE TITLE
--host_features=compiler_param_file need bazel >= 6.1.0

### ISSUE THREAD

**Issue by doupongzeng** [hedronvision/bazel-compile-commands-extractor#153]
[[6.1.0] Add --host_features](https://github.com/bazelbuild/bazel/pull/17528)

I think it's possible to add a version number check during execution; otherwise, error messages can be confusing and unclear at first.

**Comment by cpsauer** [comment]
Yes--to make sure I'm on the same page, you're running an old version of Bazel < 6.1 where our passing host_features breaks things, yes?

If you can't just update, would you be down to toss up a PR so we call `bazel version` from inside the python script and parse it and use that to gate the addition of the flag, and make sure all still works for you?

Preferably with a fn just above _get_compile_commands_for_aquery like:
```Python
@functools.lru_cache(maxsize=None)
def _get_bazel_version():
    subprocess.run(
...
return <version tuple>
```

**Comment by cpsauer** [comment]
@doupongzeng, how much do you need the old version? We're thinking about whether we need to support 6.1 in another feature, #154

**Comment by doupongzeng** [comment]
> @doupongzeng, how much do you need the old version? We're thinking about whether we need to support 6.1 in another feature, #154

I am currently using version 5.1.0, and I have temporarily removed the `--host_features=compiler_param_file`, which also works.

**Comment by cpsauer** [comment]
I understand. Is upgrading an option? And if not, would you be down to toss up a PR as above, and chime in on #154 asking for backwards compatibility? He'll know what you mean.

**Comment by doupongzeng** [comment]
> I understand. Is upgrading an option? And if not, would you be down to toss up a PR as above, and chime in on #154 asking for backwards compatibility? He'll know what you mean.我明白。升级是一种选择吗？如果没有，您是否会像上面那样提交一个 PR，并在 #154 上插话要求向后兼容？他会明白你的意思。

Sure, I can try this weekend. Upgrading the version seems infeasible right now.

**Comment by doupongzeng** [comment]
> I understand. Is upgrading an option? And if not, would you be down to toss up a PR as above, and chime in on #154 asking for backwards compatibility? He'll know what you mean.

Sure, I can try this weekend. Upgrading the version seems infeasible right now.
