### ISSUE TITLE
Install instructions can't be taken literally

### ISSUE THREAD

**Issue by jwbee** [hedronvision/bazel-compile-commands-extractor#20]
What is `ln -s bazel-out/../../../external .` supposed to mean in practice? It clearly cannot be taken literally. Is `../../../` meant to stand in for something like `k8-opt` or `k8-fastbuild` and if so, how is the user meant to switch between toolchain configs?

**Comment by matta** [comment]
I think it really is meant to be taken literally.  I copy/pasted the command and it worked for me.

In your project root, next to the `WORKSPACE` file, run

```
ln -s bazel-out/../../../external
```

It creates a link like this:

```
$ ls -l external
external -> bazel-out/../../../external/
```

Note that `bazel-out` itself is a symbolic link:

```
$ ls -l bazel-out
/home/matt/.cache/bazel/_bazel_matt/b06faae89ff42e5fae839cbe27f8d9e7/execroot/__main__/bazel-out/
```

And the relative path resolves to this:

```
$ realpath external
/home/matt/.cache/bazel/_bazel_matt/b06faae89ff42e5fae839cbe27f8d9e7/external
$ ls external/.
...lots of files...
```

**Comment by cpsauer** [comment]
Yep! Definitely intended to be taken literally. Matt's answer is right on the money. Should work correctly automatically for all configs! 
(Thank you, Matt! Love that you beat me to it :)
@jwbee, is there text you think we should add to the README that would help resolve ambiguity?

And thank you both for giving the tool a try! Would (always) love to hear what you're using the tool for and how it's going. 

Back to the symlink: If you're curious what's going on under the hood and why it points there, into the output base, there's some good discussion in the [Implementation Readme](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/ImplementationReadme.md#more-details-on-external). There's also some discussion higher up of why it *doesn't* point into the execroot :)

**Comment by jwbee** [comment]
Clearly, I need to learn to interpret broken NFS mounts correctly. Thanks for the advice!

**Comment by cpsauer** [comment]
No, no. Thanks for playing with it, asking, and figuring things out!
I'm all the more curious what setup you've got that integrates both this and NFS!
