### ISSUE TITLE
Is this repo not maintained anymore?

### ISSUE THREAD

**Issue by xradgul** [hedronvision/bazel-compile-commands-extractor#232]
The main branch is broken. The [fix](https://github.com/hedronvision/bazel-compile-commands-extractor/pull/219) was never merged since several months, despite a number of recently reported issues. If that is the intention, then a disclaimer in readme can save folks hours of wasted effort. Happy to send a PR (just looking for a confirmation).

**Comment by sthornington** [comment]
I fear it might be, haven't heard a peep from Chris in a few months.  If someone wants to take over a fork I'm happy to tidy up my stuff that we are using into a proper PR: https://github.com/hedronvision/bazel-compile-commands-extractor/pull/215

**Comment by xradgul** [comment]
Congratulations on joining DeepMind! And great to know that the repo isn't abandoned.

**Comment by sthornington** [comment]
Any update on this ?

**Comment by kenroser** [comment]
On the 1 year anniversary of cpsauer saying this project is not dead, it apparently is.
