### ISSUE TITLE
Unrecognized option: --ui_event_filters=-info

### ISSUE THREAD

**Issue by johnzeng** [hedronvision/bazel-compile-commands-extractor#31]
Hi, when I use the latest version of this repo and got this error message:
```
>>> Analyzing commands used in @//...
ERROR: Unrecognized option: --ui_event_filters=-info
aquery failed. Command: bazel aquery 'mnemonic('"'"'(Objc|Cpp)Compile'"'"',deps(@//...))' --output=jsonproto --ui_event_filters=-info --noshow_progress
>>> Failed extracting commands for @//...
    Continuing gracefully...
```

I found something here:
```
./hedron_compile_commands/refresh.template.py:        "--ui_event_filters=-info",
```

so I just comment it
```
./hedron_compile_commands/refresh.template.py:       # "--ui_event_filters=-info",
```

And than erverthing is fine.

I don't know why(I'm new in bazel) but it looks like a bug?

**Comment by cpsauer** [comment]
Hi, @johnzeng! Thanks for trying the tool--and for your persistence in getting things working. Sorry it gave you some trouble.

What's strange is that flag is passed on every run--and there are quite a few people using the tool these days. To make sure I wasn't going crazy or something, I just tested it on the latest Bazel release and rolling release and don't see that error.

Aha! I can, however, trigger the error with very old versions of Bazel that don't support that flag. 4.0.0 works, but 3.0.0 fails with that message. Could I ask you to run `bazel --version` for me to check if that's it? If it shows something older than like 5.0.0, it's well worth updating! 

If that's the cause of the issue, I'd strongly recommend using [bazelisk](https://github.com/bazelbuild/bazelisk). That way you'll always be up to date! I like being on the rolling releases, so I get fixes in a timely fashion. (`echo rolling > .bazelversion`)

If that's not the issue...I'd really like to get the the bottom of it! So please tell me anything usual about your setup that might be getting us different results :)

Thanks!
Chris

**Comment by cpsauer** [comment]
I'm going to close this (optimistically), since I haven't heard from you in a few days and an old Bazel version seems likely.
But if that's not it, please let me know, and I'll reopen this issue and jump right back in with you.

**Comment by cpsauer** [comment]
Hey, @johnzeng, following up: Did this resolve things for you?

**Comment by johnzeng** [comment]
Build label: 2.1.0 
This bazel is shipped with my company's building system, so I can't just upgrade it.
Any way, I just forked this repo and fix it on my own repo, so don't worry about it.

**Comment by cpsauer** [comment]
Glad that's working for you!

Bummer to be stuck with an old version, though, since there are a lot of problems in those old Bazel versions as I recall.

Best of luck!
Chris
