### ISSUE TITLE
work with bazel new_local_repository error

### ISSUE THREAD

**Issue by 959YLX** [hedronvision/bazel-compile-commands-extractor#43]
Hi, thanks for create such useful tool. I'm meet some trouble when work with bazel new_local_repository.
when I using new_local_repository to add my local openssl as a repository to my project, the ```external/openssl/include``` will soft link to ```/usr/include```
```bazel
# workspace.bzl
native.new_local_repository(
    name = "openssl",
    path = "/usr",
    build_file = clean_dep("//third_party/openssl:BUILD"),
)
```
clangd will throw a error, ```In included file: 'stdlib.h' file not found```,  when I open source code which include ```iostream```, ```string```, etc...
```
In file included from /usr/include/c++/10/ext/string_conversions.h:41,
                 from /usr/include/c++/10/bits/basic_string.h:6535,
                 from /usr/include/c++/10/string:55,
                 from bazel-out/k8-fastbuild/bin/app/demo/arena-demo.pb.h:8,
                 from bazel-out/k8-fastbuild/bin/app/demo/arena-demo.trpc.pb.h:8,
                 from ./app/demo/demo_service.h:6,
                 from /root/workspace/test_project/demo/app/demo/demo_service.cc:4:
/usr/include/c++/10/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
```
I try to find some message in clangd log, and I find ```..."-isystem","external/openssl/include",...``` in ```compile_command.json```, it will cause gcc to think /usr/include is already included. So I try to compile with -v parameter and the gcc output proves it
 ```ignoring duplicate directory "/usr/include"```
In gcc10, cstdlib will using ```#include_next<stdlib.h>``` to find next stdlib.h in search path, but ```external/openssl/include``` is in front of ```/usr/include/c++/10```, so it cannot find another **stdlib.h** file.
Now I temporarily removed the openssl dependency, Hope you can provide some useful help, Thanks~

**Comment by cpsauer** [comment]
Hi, @959YLX,

You're very welcome. Thanks for giving the tool a whirl, and I'm sorry things aren't going as smoothly as either of us would like.. 

I'd like to help, but I'm not quite sure what's going on with this overall setup--and this is definitely a new kind of error. You're setting up a new_local_repository called openssl, but that's pointing into the whole of /usr, right? Shouldn't it point into the openssl subdirectory? Maybe I'm missing something.

Does the repo `bazel build` successfully otherwise? If you run the command from compile_commands.json, does it work?

All the best,
Chris

**Comment by 959YLX** [comment]
Thank you for your reply~
I uploaded a simple example on my github: [bazel_with_clangd_error](https://github.com/959YLX/bazel_with_clangd_error), it might help you understand what's going on.

Here is some info about my environment, openssl library is installed by package manager.
```
bash-4.4# gcc --version                       
gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

bash-4.4# bazel info release
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 25020dc8-cc2c-4905-bc17-2cc13506c33e
release 4.2.2
bash-4.4# clang --version
clang version 14.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
bash-4.4# clangd --version
clangd version 14.0.0
Features: linux
Platform: x86_64-unknown-linux-gnu
bash-4.4# 
```
 
In this demo project, ```bazel build ...``` or ```bazel run main``` is ok. I have generated the ```compile_command.json``` file using the command ```bazel run RefreshCompileCommands```.

I try to execute command from clangd log directly (I think it's same with command in compile_command.json), then encountered the same problem.
```
/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -std=c++0x -MD -MF bazel-out/k8-fastbuild/bin/_objs/main/main.pic.d -frandom-seed=bazel-out/k8-fastbuild/bin/_objs/main/main.pic.o -fPIC -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/openssl -iquote bazel-out/k8-fastbuild/bin/external/openssl -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/bin/external/bazel_tools -isystem external/openssl/include -isystem bazel-out/k8-fastbuild/bin/external/openssl/include -Wno-builtin-macro-redefined "-D__DATE__=\"redacted\"" "-D__TIMESTAMP__=\"redacted\"" "-D__TIME__=\"redacted\"" -c /root/workspace/bazel_with_clangd_error/main.cc -o bazel-out/k8-fastbuild/bin/_objs/main/main.pic.o
```
```
In file included from /usr/include/c++/10/ext/string_conversions.h:41,
                 from /usr/include/c++/10/bits/basic_string.h:6535,
                 from /usr/include/c++/10/string:55,
                 from /usr/include/c++/10/bits/locale_classes.h:40,
                 from /usr/include/c++/10/bits/ios_base.h:41,
                 from /usr/include/c++/10/ios:42,
                 from /usr/include/c++/10/ostream:38,
                 from /usr/include/c++/10/iostream:39,
                 from /root/workspace/bazel_with_clangd_error/main.cc:1:
/usr/include/c++/10/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
```

**Comment by cpsauer** [comment]
Huh! What's weird is that's exactly the command bazel should be executing.

Thanks for making a minimal example. I'll take a quick peek--but I've got to go to bed pretty soon. (It's late here.)

**Comment by cpsauer** [comment]
On your end, any ideas what's going on? Thoughts on the new_local_repository questions, above?

**Comment by 959YLX** [comment]
Thanks and good night~
I don't have a good idea yet, maybe openssl should only soft link to ```/usr/include/openssl``` rather than ```/usr/include```?

**Comment by cpsauer** [comment]
Have your example open, but yeah, I better crash. (Also don't have a linux machine handy right now unfortunately.)

**Comment by cpsauer** [comment]
I would think, maybe, that you might not even need the new_local_repository to pick up openssl. Wouldn't those folders it already be part of your default header search paths? (And link paths?)

**Comment by 959YLX** [comment]
Yes, ```/usr/include/openssl```is already a part of my default header search paths.
That is a piece of code in the framework, maybe I should ask my colleagues if it is possible to remove the use of new_local_repository.

**Comment by cpsauer** [comment]
@959YLX, I'm going to close this down since I haven't heard from you in a little while. But if that didn't work--or you'd like to explore--just lmk and I'll open this right back up
