### ISSUE TITLE
FATAL ERROR: Python 3.7 or later is required. Please update!

### ISSUE THREAD

**Issue by cloudhan** [hedronvision/bazel-compile-commands-extractor#46]
This is caused by system python version is too old. Boring issue. The interesting part is that https://github.com/bazelbuild/rules_python supports hermetic Python toolchain that the rule handles downloading the interpreter automatically. I think `hedron_compile_commands_setup()` should be expanded to `hedron_compile_commands_setup(use_system_python=False)` (where `use_system_python` default to have `True` value) and automatically setup the toolchain it needs.

**Comment by cpsauer** [comment]
Ooh. An interesting part indeed. I didn't realize they'd started supporting hermetic Python. Thanks for an interesting suggestion--and for playing around with this tool. I also like your writing style.

I'd be excited about the idea of having the tool get the Python it needs--even as a default--if you're excited enough to build this out?

Some things that occur as nice and exciting:
- We could eliminate this error case, and make sure we always come with batteries included.
  - The use of Python is really an implementation detail, so I'd be happy to get it out of the interface.
- We could update our python version, and get rid of backwards compatibility cruft. (See the MIN_PY stuff near that error message).
  - Another alternative, I suppose, is to *only* grab hermetic python if the system python isn't new enough.

Some things we'd want to make sure were okay:
- From their docs, it looks like the python toolchain is inferred by py_binary, so we'd need to be careful to not mess up people's existing setups. If we can't do this, maybe people should (separately) be adding the toolchain to their workspaces--or just updating their system Python.

Cheers!
Chris

**Comment by cloudhan** [comment]
After brief exploring, it would uncessarirly complicate the workspace setup. So I think it is better to let the user to supply a python path via a flag in this case, e.g.: 
```bash
bazel run --@hedron_compile_commands//:python_path=<python_to_use> @hedron_compile_commands//:refresh_all -- --config=Debug --compilation_mode=dbg
```

But anyway, if the python version met the requirement, this tool works like a charm! Love it.

**Comment by cpsauer** [comment]
Oh bummer.

Just to make sure I'm understanding, @cloudhan, you're pinned to an older Python version than the one needed by this tool, and therefore can't just update?

There's got to be a Bazel way to control the Python version by build, though, right? How about just passing that in when invoking the tool? Would that work?

**Comment by cpsauer** [comment]
@cloudhan, where are we at on this?

If, e.g., you found a way to set python version by build, then it might be worth posting for others!

**Comment by cloudhan** [comment]
The easy way is to install miniconda. It can install any version of python without interfering with system python :)

**Comment by cpsauer** [comment]
Miniconda I've used, but never with Bazel! Am I understanding correctly that you're suggesting setting the python environment and then invoking `bazel run` to use different python versions for different targets?

---

I'm going to close this issue for now--but lmk if you'd still like it open. The reasoning is that it sounds like you've determined it's not feasible/worth it to bundle hermetic python just for this rule with the current Bazel support, and it seems like setting python version by target is something we should be getting from Bazel rather than rolling ourselves.

**Comment by cameron-martin** [comment]
I think this should be possible. If you don't register the toolchains and instead use the toolchain directly, you should be able to not interfere with the python version used elsewhere.

**Comment by cpsauer** [comment]
@cameron-martin, is this something we should make code changes to support, or something that would already work with Bazel's existing toolchain flags?

**Comment by cameron-martin** [comment]
I may have been overconfident. I took a look at this earlier and it wasn't as easy as I thought. Theres a related issue here: https://github.com/bazelbuild/rules_python/issues/728
