### ISSUE TITLE
mypy correctness

### ISSUE THREAD

**Issue by pqn** [hedronvision/bazel-compile-commands-extractor#47]
We're using https://github.com/thundergolfer/bazel-mypy-integration, and I encountered the following issue in our CI in my `//:refresh_compile_commands` target:

```
bazel-out/k8-opt/bin/refresh_compile_commands.py:67: error: "Callable[[], Any]" has no attribute "has_logged"
bazel-out/k8-opt/bin/refresh_compile_commands.py:95: error: Incompatible types in assignment (expression has type "List[str]", variable has type "Generator[str, None, None]")
bazel-out/k8-opt/bin/refresh_compile_commands.py:97: error: No overload variant of "run" matches argument types "Generator[str, None, None]", "bool", "str", "bool"
bazel-out/k8-opt/bin/refresh_compile_commands.py:97: note: Possible overload variants:
bazel-out/k8-opt/bin/refresh_compile_commands.py:97: note:     def run(args: Union[Union[bytes, str], Sequence[Union[str, bytes, _PathLike[str], _PathLike[bytes]]]], bufsize: int = ..., executable: Union[str, bytes, _PathLike[str], _PathLike[bytes], None] = ..., stdin: Union[None, int, IO[Any]] = ..., stdout: Union[None, int, IO[Any]] = ..., stderr: Union[None, int, IO[Any]] = ..., preexec_fn: Callable[[], Any] = ..., close_fds: bool = ..., shell: bool = ..., cwd: Union[str, bytes, _PathLike[str], _PathLike[bytes], None] = ..., env: Union[Mapping[bytes, Union[bytes, str]], Mapping[str, Union[bytes, str]], None] = ..., universal_newlines: bool = ..., startupinfo: Any = ..., creationflags: int = ..., restore_signals: bool = ..., start_new_session: bool = ..., pass_fds: Any = ..., *, capture_output: bool = ..., check: bool = ..., encoding: str, errors: Optional[str] = ..., input: Optional[str] = ..., text: Optional[bool] = ..., timeout: Optional[float] = ...) -> CompletedProcess[str]
bazel-out/k8-opt/bin/refresh_compile_commands.py:97: note:     def run(args: Union[Union[bytes, str], Sequence[Union[str, bytes, _PathLike[str], _PathLike[bytes]]]], bufsize: int = ..., executable: Union[str, bytes, _PathLike[str], _PathLike[bytes], None] = ..., stdin: Union[None, int, IO[Any]] = ..., stdout: Union[None, int, IO[Any]] = ..., stderr: Union[None, int, IO[Any]] = ..., preexec_fn: Callable[[], Any] = ..., close_fds: bool = ..., shell: bool = ..., cwd: Union[str, bytes, _PathLike[str], _PathLike[bytes], None] = ..., env: Union[Mapping[bytes, Union[bytes, str]], Mapping[str, Union[bytes, str]], None] = ..., universal_newlines: Literal[False] = ..., startupinfo: Any = ..., creationflags: int = ..., restore_signals: bool = ..., start_new_session: bool = ..., pass_fds: Any = ..., *, capture_output: bool = ..., check: bool = ..., encoding: None = ..., errors: None = ..., input: Optional[bytes] = ..., text: Optional[Literal[False]] = ..., timeout: Optional[float] = ...) -> CompletedProcess[bytes]
bazel-out/k8-opt/bin/refresh_compile_commands.py:97: note:     def run(args: Union[Union[bytes, str], Sequence[Union[str, bytes, _PathLike[str], _PathLike[bytes]]]], bufsize: int = ..., executable: Union[str, bytes, _PathLike[str], _PathLike[bytes], None] = ..., stdin: Union[None, int, IO[Any]] = ..., stdout: Union[None, int, IO[Any]] = ..., stderr: Union[None, int, IO[Any]] = ..., preexec_fn: Callable[[], Any] = ..., close_fds: bool = ..., shell: bool = ..., cwd: Union[str, bytes, _PathLike[str], _PathLike[bytes], None] = ..., env: Union[Mapping[bytes, Union[bytes, str]], Mapping[str, Union[bytes, str]], None] = ..., universal_newlines: bool = ..., startupinfo: Any = ..., creationflags: int = ..., restore_signals: bool = ..., start_new_session: bool = ..., pass_fds: Any = ..., *, capture_output: bool = ..., check: bool = ..., encoding: Optional[str] = ..., errors: Optional[str] = ..., input: Union[bytes, str, None] = ..., text: Optional[bool] = ..., timeout: Optional[float] = ...) -> CompletedProcess[Any]
bazel-out/k8-opt/bin/refresh_compile_commands.py:97: note:     <3 more non-matching overloads not shown>
bazel-out/k8-opt/bin/refresh_compile_commands.py:216: error: "Callable[[List[str], str], Any]" has no attribute "has_logged_missing_file_error"
bazel-out/k8-opt/bin/refresh_compile_commands.py:217: error: "Callable[[List[str], str], Any]" has no attribute "has_logged_missing_file_error"
```

A good fix would be to enforce mypy in this repo, but it might suffice for now if I can somehow pass a `manual` tag to the `py_binary` defined here, just so I can pass CI: https://github.com/hedronvision/bazel-compile-commands-extractor/blob/0fe77b07dafed4b7172aced71108bc30d2a42ef5/refresh_compile_commands.bzl#L54

Maybe just add a `kwargs` field to `refresh_compile_commands` that forwards to the `py_binary`?
https://github.com/hedronvision/bazel-compile-commands-extractor/blob/0fe77b07dafed4b7172aced71108bc30d2a42ef5/refresh_compile_commands.bzl#L42

**Comment by cpsauer** [comment]
Hey, Prem! Good to hear from you.

Offhand, looking at mypy's "errors," they seem more like false positives than things we should enforce. The first and last are about using a variable on a function to have semantics similar to a C static local rather than using a global (handy!). And the middle one is mypy treating as an issue the chaining of generators before materializing. All those cases definitely use Python features in a way that you'd be unlikely to be able to in a statically typed language, but that's not so bad, since they're valid, useful, and safe. Basically, I'm not sold on mypy if those are its errors :) Please do lmk if you think I'm wrong!

If that's right, then I think probably we just want to disable your mypy run over this. Will tagging "manual" actually do it? I'd think that you'd still get the errors when you tried to build manually given the setup in their README. But if that works, how about if we just pipe that tags attribute through to (both?) rules in the macro. Not sure we should have people start depending on it being a py_binary in the macro, since that's more of an implementation detail. Or actually, even better, to automatically support [a more full set of common attributes](https://docs.bazel.build/versions/main/be/common-definitions.html#common-attributes), how about if piped the kwargs to *both* rules inside the macro?

Cheers--and sorry this is a hassle.
Chris

**Comment by pqn** [comment]
Thanks for the quick reply as always Chris! :)

> Offhand, looking at mypy's "errors," they seem more like false positives than things we should enforce. The first and last are about using a variable on a function to have semantics similar to a C static local rather than using a global (handy!). And the middle one is mypy treating as an issue the chaining of generators before materializing. All those cases definitely use Python features in a way that you'd be unlikely to be able to in a statically typed language, but that's not so bad, since they're valid, useful, and safe. Basically, I'm not sold on mypy if those are its errors :) Please do lmk if you think I'm wrong!

I'm also inclined to dismiss the errors as not very useful for similar reasoning to yours, so in this case "enforce mypy" would mean just locally disabling those warnings.

> If that's right, then I think probably we just want to disable your mypy run over this. Will tagging "manual" actually do it?

Yes, the reason "manual" works is that our CI is building `//...` which excludes the "manual" tag. We only run the mypy aspect in CI (and only in some parts) and not usually locally.

> I'd think that you'd still get the errors when you tried to build manually given the setup in their README. But if that works, how about if we just pipe that tags attribute through to (both?) rules in the macro. Not sure we should have people start depending on it being a py_binary in the macro, since that's more of an implementation detail. Or actually, even better, to automatically support [a more full set of common attributes](https://docs.bazel.build/versions/main/be/common-definitions.html#common-attributes), how about if piped the kwargs to both rules inside the macro?

That solution works for me!

**Comment by cpsauer** [comment]
Trying :) Especially for you, Prem.
(Obv you're always welcome to text or talk live if easier, but this is good, too.)

**Comment by cpsauer** [comment]
Just pushed the joint kwargs solution to try to get the intersection of the common attributes. Hopefully that unblocks things for you.

**Comment by cpsauer** [comment]
I think it's good we added it--like this "rule" should really support tags and compatible_with and the full complement of common attributes.

But also I realized that there might be easier and more direct ways for you guys to exclude it from CI. The target patterns in a build can take exclusions, like `bazel build -- foo/... -foo/bar/...` (search that on this page for more if you want https://docs.bazel.build/versions/main/guide.html#specifying-targets-to-build)

[Previously, I thought you were running mypy on *all* builds like in their readme. Makes sense that you could use a manual tag to dodge a single target pattern, but then it occurred that maybe it was easier to just exclude it from the pattern.]

**Comment by cpsauer** [comment]
Anyway, I'm going to close this for now (optimistically). But please do lmk whether this works for you. And if not, I'll open this right back up.

**Comment by pqn** [comment]
> Just pushed the joint kwargs solution to try to get the intersection of the common attributes. Hopefully that unblocks things for you.

Awesome, thanks!!

> The target patterns in a build can take exclusions, like `bazel build -- foo/... -foo/bar/...`

This definitely also works. We've adopted a policy of using tags  (`manual` being just one of them) with `--test_tag_filters` and `--build_tag_filters` to block entire categories of targets for certain CI commands for various reasons. So we didn't go with this previously just for the sake of command brevity.

> Anyway, I'm going to close this for now (optimistically). But please do lmk whether this works for you. And if not, I'll open this right back up.

Keeping it closed SGTM.

**Comment by cpsauer** [comment]
Sweet :)
[Surprised you're still up!]
