### ISSUE TITLE
On MacOS Monterey 12.4 with XCode 13.4, clang complains of no sysroot

### ISSUE THREAD

**Issue by jiawen** [hedronvision/bazel-compile-commands-extractor#68]
I'm using a vanilla MacOS with XCode environment - on a freshly installed Apple Studio (M1 Ultra) and Bazel 5.2.0-homebrew. I'm using option 3 (BUILD with refresh_compile_commands).

I tried a single `cc_library` target and it complains that:

```
>>> While locating the headers you use, we encountered a compiler warning or error.
    No need to worry; your code doesn't have to compile for this tool to work.
    However, we'll still print the errors and warnings in case they're helpful for you in fixing them.
    If the errors are about missing files that Bazel should generate:
        You might want to run a build of your code with --keep_going.
        That way, everything possible is generated, browsable and indexed for autocomplete.
    But, if you have *already* built your code successfully:
        Please make sure you're supplying this tool with the same flags you use to build.
        You can either use a refresh_compile_commands rule or the special -- syntax. Please see the README.
        [Supplying flags normally won't work. That just causes this tool to be built with those flags.]
    Continuing gracefully...
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk' [-Wmissing-sysroot]

(several more instances)

>>> Finished extracting commands for <redacted>
```

And indeed, the path `/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` does not exist. [It looks like it moved](https://github.com/actions/virtual-environments/issues/2211) and is now at `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`. This is a symlink to its siblings reflecting the latest version on the system.

I assume this isn't a `bazel-compile-commands-extractor` bug. But I don't know Bazel's toolchain resolution logic well enough to figure out where that path is baked in.

Any ideas?

**Comment by cpsauer** [comment]
Hey, @jiawen, fellow Xoogler! Thanks for using the tool and writing in. I smiled seeing you file these two and reply to the NDK issue back to back to back.

I think there's a good chance this is our issue, assuming the cc_library builds fine under Bazel normally. Which it does, right?

[In the background, we have to infer the SDKROOT, since [Bazel has a bug](https://github.com/bazelbuild/bazel/issues/12852) where they omit many environment variables from the action information--and in working around that but, I bet we have things a bit more hardcoded than we should.]

Could I ask you to check that `xcrun --show-sdk-path -sdk macosx` gives you the correct path? And that `xcode-select --print-path` returns that CommandLineTools folder? (I'm asking because my machine is set up with Xcode, for which these other paths remain correct.)

I've got to crash for now, but I'll return to this tm.

Thanks for your help and patience!
Chris

**Comment by jiawen** [comment]
Hi Chris,

Nice to finally meet you! I've been impressed at the open source work you've been doing.

Yes, the `cc_library` target works builds fine under Bazel normally :).

```
$ xcrun --show-sdk-path -sdk macosx
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

```
$ xcode-select --print-path
/Library/Developer/CommandLineTools
```

```
$ ls -la /Library/Developer/CommandLineTools
total 0
drwxr-xr-x 5 root wheel 160 Jun 29 11:31 ./
drwxr-xr-x 4 root admin 128 Jun 29 11:31 ../
drwxr-xr-x 5 root wheel 160 Apr 29 22:20 Library/
drwxr-xr-x 7 root wheel 224 Jun 29 11:31 SDKs/
drwxr-xr-x 7 root wheel 224 Apr 29 22:22 usr/
```

```
$ ls -la /Library/Developer/CommandLineTools/SDKs
total 0
drwxr-xr-x 7 root wheel 224 Jun 29 11:31 ./
drwxr-xr-x 5 root wheel 160 Jun 29 11:31 ../
lrwxr-xr-x 1 root wheel  14 Jun 29 11:31 MacOSX.sdk -> MacOSX12.3.sdk/
drwxr-xr-x 7 root wheel 224 Mar 31 07:00 MacOSX11.3.sdk/
lrwxr-xr-x 1 root wheel  14 Jun 29 11:31 MacOSX11.sdk -> MacOSX11.3.sdk/
drwxr-xr-x 7 root wheel 224 Mar 31 06:56 MacOSX12.3.sdk/
lrwxr-xr-x 1 root wheel  14 Jun 29 11:31 MacOSX12.sdk -> MacOSX12.3.sdk/
```

**Comment by cpsauer** [comment]
:) Thanks for being so kind--and thorough.

Definitely our problem, then--and a result of my hardcoding in [_get_apple_SDKROOT](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/30149bdadf7b1d0b0367592bfb4864318202765d/refresh.template.py#L509). Sorry about that. Thanks for reporting!

**Comment by cpsauer** [comment]
I just pushed a commit that should fix this. Could you give the latest a try, and tell me if it fixes things for you?
[I've closed the issue (optimistically) but I'll open it right back up if that doesn't fix things.]

Separately, you've got me curious! What's this image_io you're working on? Could I ask you to run `xcrun --find clang` on your machine, just for the completeness of my comments? And I'm curious where else (if anywhere besides that NDK issue) you might have run into me on GitHub!

Cheers! Hope that works. And again, sorry it didn't just work out of the box.
Chris

**Comment by jiawen** [comment]
Just gave it a try - it works!

@image_io: haha, that's just my wrapper around libpng. Nothing fancy - but I plan to open source it since it's way either with Bazel than anything else on the planet.

```
$ xcrun --find clang
/Library/Developer/CommandLineTools/usr/bin/clang
```

I think I've mostly run into your various comments in the Bazel / Objective C world. I must say, `bazel-compile-commands-extractor`'s README is excellent - very refreshing.

**Comment by cpsauer** [comment]
Yay! Delighted to hear it, and again, thanks for being great to work with and for bearing with me.

Sounds great! Looking forward to using it someday :)

**Comment by joneshf** [comment]
👋 Just passed by this issue while trying to diagnose something that's unrelated to this project. It was a very wholesome conversation. I have nothing to contribute, but it was nice to read.
