### ISSUE TITLE
assert when executing  "bazel run //:refresh_compile_commands"

### ISSUE THREAD

**Issue by lixiaoquan** [hedronvision/bazel-compile-commands-extractor#7]
Thanks for this tool, it is very easy to setup. I am not sure this is the right place to raise a question.

I run into this error when trying to extract compile_command.json from this project

https://github.com/larq/compute-engine

```text
  File "/home/xiaoquan.li/.cache/bazel/_bazel_xiaoquan.li/3668b3601d2bf895d72824373699ee16/execroot/larq_compute_engine/bazel-out/k8-opt/bin/external/hedron_compile_commands/extract.runfiles/hedron_compile_commands/extract.py", line 201, in <module>
    for files, command in outputs:
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/xiaoquan.li/.cache/bazel/_bazel_xiaoquan.li/3668b3601d2bf895d72824373699ee16/execroot/larq_compute_engine/bazel-out/k8-opt/bin/external/hedron_compile_commands/extract.runfiles/hedron_compile_commands/extract.py", line 183, in _get_cpp_command_for_files
    files = _get_files(args)
  File "/home/xiaoquan.li/.cache/bazel/_bazel_xiaoquan.li/3668b3601d2bf895d72824373699ee16/execroot/larq_compute_engine/bazel-out/k8-opt/bin/external/hedron_compile_commands/extract.runfiles/hedron_compile_commands/extract.py", line 81, in _get_files
    files = source_files + _get_headers(compile_args, source_files[0])
  File "/home/xiaoquan.li/.cache/bazel/_bazel_xiaoquan.li/3668b3601d2bf895d72824373699ee16/execroot/larq_compute_engine/bazel-out/k8-opt/bin/external/hedron_compile_commands/extract.runfiles/hedron_compile_commands/extract.py", line 64, in _get_headers
    assert len(headers) == len(set(headers)), "Compiler should have ensured uniqueness of header files"
AssertionError: Compiler should have ensured uniqueness of header files
 >>> Finished extracting commands for //larq_compute_engine/mlir:lce-tf-opt
```

This is how I setup bazel-compile-commands-extractor for this target (this target can be built successfully)

```text
diff --git a/BUILD b/BUILD
index 27aee18..fe0cf9a 100644
--- a/BUILD
+++ b/BUILD
@@ -9,3 +9,17 @@ sh_binary(
         "//larq_compute_engine:compute_engine_py",
     ],
 )
+
+load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")
+
+refresh_compile_commands(
+    name = "refresh_compile_commands",
+
+    # Specify the targets of interest.
+    # For example, specify a dict of targets and their arguments:
+    targets = {
+        "//larq_compute_engine/mlir:lce-tf-opt": ""
+    },
+    # For more details, feel free to look into refresh_compile_commands.bzl if you want.
+)
+
diff --git a/WORKSPACE b/WORKSPACE
index 5a415a2..9cdc5e2 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -39,3 +39,17 @@ tf_workspace1()
 load("@org_tensorflow//tensorflow:workspace0.bzl", "tf_workspace0")

 tf_workspace0()
+
+# Hedron's Compile Commands Extractor for Bazel
+# https://github.com/hedronvision/bazel-compile-commands-extractor
+http_archive(
+    name = "hedron_compile_commands",
+
+    # Replace the commit hash in both places (below) with the latest.
+    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" below).
+    url = "https://github.com/hedronvision/bazel-compile-commands-extractor/archive/9d8b3d5925728c3206010ed0062826a9faaebc2c.tar.gz",
+    strip_prefix = "bazel-compile-commands-extractor-9d8b3d5925728c3206010ed0062826a9faaebc2c",
+)
+load("@hedron_compile_commands//:workspace_setup.bzl", "hedron_compile_commands_setup")
+hedron_compile_commands_setup()
+
(END)
```

**Comment by cpsauer** [comment]
Hey, @lixiaoquan! Definitely the right place to ask questions--and I'm glad you found the setup easy. Thanks for giving it a try :) Appreciate you reporting the issue so we can fix things for everyone. And my apologies that the issue was there in the first place.

I'll dive in and see if I can get things set up.

Out of curiosity, could I ask what OS you're using? (Also curious what you're hacking on! Looks like a neat library.)

**Comment by lixiaoquan** [comment]
@cpsauer Thanks for a quick response.

I'm testing all this in a docker based on ubuntu18.04

As for https://github.com/larq/compute-engine, I'm trying to dig into its mlir-based converter which can lower a TF model to optimized model. Since this converter depends on some TF C++ code and LLVM C++ code, I hope to get a compile_commands.json file to use clangd.

**Comment by cpsauer** [comment]
Ugh, sadly, I'm having trouble repro'ing over here. I think I may need your help.

[I'm on macOS and can generate a compile_commands.json that looks good for the repo/diff you posted--without hitting that assert. I did so without having built the repo, so I'm currently running a build to see if it changes anything.]

I'm seeing some other things improve along the way--pushing those up as I go :) Thanks for handing over an interesting test case.

For context: The assert being hit is from part of the code that finds the headers use by a given source file. This is used to help clangd know which flags are used when compiling that header.  It draws upon clang do to so. I'm surprised to see that Clang's dependent files output would list duplicate dependencies (hence the assert) but I'd guess it's something innocent. Worst case, I'll just enforce the constraint I formerly asserted.

**Comment by cpsauer** [comment]
Aha! A container on Ubuntu. Just read your reply.

If you'd be down to get into the code, any chance you'd be down to dump out the contents of headers_makefile_out just before that assert?

Easiest would probably be to just go into //external/hedron_compile_commands/extract.py and add
`print(headers_makefile_out)` right above the assert.

[Could also set things up for local development, which is pretty easy. Good instructions in https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/ImplementationReadme.md]

**Comment by cpsauer** [comment]
In addition, any guidance on getting a container setup to match yours?
(Haven't yet used Bazel w/ Docker.)

**Comment by cpsauer** [comment]
Build finished, but no luck; things are still working over here on macOS.

My guess is that clang's output format for dependency file generation differs by platform. I could just pull out the assert. However, I'd really like to double check that guess first, to make sure we're not missing anything. (Hence the request for the contents of that variable or help getting me set up the same way you are.)

Again, thanks for submitting the issue! I appreciate your patience with this first version.

**Comment by lixiaoquan** [comment]
I guess this may cause by difference between g++ and clang, unfortunately I can't get clang setup in docker for some reason.
If I did so, gcc still looks for cc1plus.  This is my Dockerfile 
```
FROM ubuntu:18.04

RUN apt-get update --fix-missing

RUN apt-get update && apt-get install -y --no-install-recommends wget g++ sudo

RUN apt-get install -y --no-install-recommends silversearcher-ag ninja-build less patch git rsync

RUN wget --no-check-certificate -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64
RUN chmod +x /usr/local/bin/bazel

RUN apt-get install -y software-properties-common
RUN apt-get install -y python3-dev python3-setuptools

RUN cd /tmp && wget -q https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py

RUN ln -s /usr/bin/python3 /usr/local/bin/python
RUN ln -s /usr/bin/python3 /usr/bin/python
```

**Comment by cpsauer** [comment]
I think that's a very good guess. Would love to get a snippet of the Ubuntu g++ formatting to hack on.

Before I try to pull that whole image, any chance I could ask you to try to dump the output to your console and send it to me? (using the instructions in https://github.com/hedronvision/bazel-compile-commands-extractor/issues/7#issuecomment-974998047)  If you run into a roadblock, just lmk and I'll work on building the container.

**Comment by lixiaoquan** [comment]
This is log before assert, I got it by adding a few prints before assert.
```python
import sys
sys.stderr.write("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n")
sys.stderr.write("{}\n".format(len(headers)))
sys.stderr.write("{}\n".format(len(set(headers))))
sys.stderr.write("{}\n".format(headers_makefile_out))
assert len(headers) == len(set(headers)), "Compiler should have ensured uniqueness of header files"
```
[1.txt](https://github.com/hedronvision/bazel-compile-commands-extractor/files/7578236/1.txt)

**Comment by lixiaoquan** [comment]
> This is log before assert, I got it by adding a few prints before assert.
> 
> ```python
> import sys
> sys.stderr.write("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n")
> sys.stderr.write("{}\n".format(len(headers)))
> sys.stderr.write("{}\n".format(len(set(headers))))
> sys.stderr.write("{}\n".format(headers_makefile_out))
> assert len(headers) == len(set(headers)), "Compiler should have ensured uniqueness of header files"
> ```
> 
> [1.txt](https://github.com/hedronvision/bazel-compile-commands-extractor/files/7578236/1.txt)

I workaround this by disabling this assert, it works now. Thanks again for this tool!

**Comment by cpsauer** [comment]
Awesome. You're super welcome. Please grab the latest commit (486d6eaf87255b7e15640bb9add58f0a77c1e2b6) in your WORKSPACE for a fix, and a bunch of other good improvements I pushed up today!

---
In more detail:
Thanks to your log, we've got more confidence on the fix. The good news is: formatting is the same for gcc...but it's still super weird that gcc is emitting duplicate entries. I've replaced the assert with some code that filters duplicates.

Please let me know if you have any more issues! Sorry this took a bit. And if you ever want to get your hands dirty with the code--say if I'm being too slow--now you know where it is.

**Comment by cpsauer** [comment]
Hey, @lixiaoquan, just wanted to check back in: 

Did this get things into a state that's useful for you?

If so, yay! If not, what would need to change to make it so?

**Comment by lixiaoquan** [comment]
@cpsauer Yes, I updated to latest and it works like a charm.

**Comment by cpsauer** [comment]
Wahoo! :)
