### ISSUE TITLE
Included dependency breaks intellisense

### ISSUE THREAD

**Issue by HaberR** [hedronvision/bazel-compile-commands-extractor#71]
I've found that including a particular dependency tends to break the intellisense derived from this project. [Here](https://github.com/thirdwave-ai/compilecommands_issue)'s a repo that you can clone to reproduce the issue--would you mind taking a look?

**Comment by cpsauer** [comment]
Hey @HaberR! Good to hear from you again. Thanks for making a sample repo.

I'm afraid I'm out of town right now--and don't have easy access to a Linux machine. Any chance I could ask you to scope things a little more for me in the meantime? What does the resulting compile_commands.json look like? If you manually run the command from the arguments list for test.cc in your workspace, does it run cleanly? And if not, is it clear what's wrong with it? If it does run cleanly, could I ask you to look at the clangd output in your editor and see if there's anything interesting there? 
(I think you're saying that adding this (unused) dependency on libpng causes header inclusion to break for you, so I'm wondering if maybe the command is getting malformed somehow.)

**Comment by cpsauer** [comment]
(back in town and debugging--making the closes macOS analogue that I can)

**Comment by cpsauer** [comment]
[I'm noticing that your new_local_repository is pulling in the whole of /usr. Maybe that's the best way to accomplish what you're going for, but it does make me a little worried. I do see that it's the largest common subpath of libpng's headers and shared library.]

**Comment by cpsauer** [comment]
Hmm, okay, no dice reproducing it that way--or with the repo unmodified.

**Comment by cpsauer** [comment]
I think I'll need a little more of your help to solve this one efficiently, along the lines in my first reply.
I presume things work correctly without pulling in /usr via the new_local_repository, right? Do things work without new_local_repository but linking via adding -lpng to the linkopts instead?

**Comment by cpsauer** [comment]
Since I haven't heard from you in the couple weeks I was gone, I'm going to close this for now, but I'll open it right back up if you reply and it's still an issue. Hopefully that's ok.
