### ISSUE TITLE
Error: invalid value in 'exclude_headers' attribute: has to be one of 'all' or 'external' instead of ''

### ISSUE THREAD

**Issue by cyy5358** [hedronvision/bazel-compile-commands-extractor#73]
Hi, I think you're making a great job!

I met a error `invalid value in 'exclude_headers' attribute: has to be one of 'all' or 'external' ` 

when running

```
bazel run @hedron_compile_commands//:refresh_all  
INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/2af04b59da0c68861770453f06c0dce8/command.profile.gz'
INFO: Invocation ID: 7fced48c-5295-4c29-87f7-ffc84ed62fd3
ERROR: /root/.cache/bazel/_bazel_root/2af04b59da0c68861770453f06c0dce8/external/hedron_compile_commands/BUILD:7:1: @hedron_compile_commands//:refresh_all.py: invalid value in 'exclude_headers' attribute: has to be one of 'all' or 'external' instead of ''
ERROR: error loading package '@hedron_compile_commands//': Package '' contains errors
INFO: Elapsed time: 0.104s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Here is my WORKSPACE file,  I had replaced latest commit

```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
http_archive(
    name = "hedron_compile_commands",
    # Replace the commit hash in both places (below) with the latest, rather than using the stale one here.
    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" in the README).
    url = "https://github.com/hedronvision/bazel-compile-commands-extractor/archive/8fd960d28648d982b90cf6e152c43ea159520cf3.tar.gz",
    strip_prefix = "bazel-compile-commands-extractor-8fd960d28648d982b90cf6e152c43ea159520cf3",
    # When you first run this tool, it'll recommend a sha256 hash to put here with a message like: "DEBUG: Rule 'hedron_compile_commands' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = ..."
)
load("@hedron_compile_commands//:workspace_setup.bzl", "hedron_compile_commands_setup")
hedron_compile_commands_setup()
```

Confused. How to make it right?

Thanks for great work again.

**Comment by cpsauer** [comment]
Hey, @cyy5358! Thanks. Any chance you're using a fairly old version of Bazel? I think that's where I've seen that error before.

**Comment by cpsauer** [comment]
Ah, yeah, I'm remembering it from https://github.com/hedronvision/bazel-compile-commands-extractor/issues/62

If you really need that old Bazel version, we could add "" to exclude_headers in refresh_compile_commands.bzl. If that works for you, please PR it up!

**Comment by cpsauer** [comment]
I'm going to close this down, since I'm optimistic that updating Bazel is the fix and didn't hear right back from you.

I know that's a little hasty. If that doesn't fix things or you need to use an old version of Bazel and want more help, just write me back and I'll open this right back up!

Cheers,
Chris

**Comment by cyy5358** [comment]
Many thanks.
Yes, I use bazel with version 1.0.0, a pretty old version indeed. :smile: :smile: :smile: 
I changed "" to exclude_headers in my fork. I would tell you if that works fines.
Actually, after my testing, bazel with version 3.5.0 fails and version 3.6.0 works. Maybe you would like to add version required statement to readme file?
Again, great job

**Comment by cpsauer** [comment]
Yay! Okay, so to confirm: The change did not work, right, and you had to upgrade to 3.6?

Since Bazel's moving fast, and there are lots of issues with older versions (and the current version!), I'm thinking most people will be pretty up to date. I could add a sanity check, but I think most people are going to be having a pretty bad time in general trying to use those old versions.

I'd highly recommend bazelisk, if you aren't already using it!

**Comment by cyy5358** [comment]
I'm using bazelisk, it's very convenient to change bazel version.
```Actually, after my testing, bazel with version 3.5.0 fails and version 3.6.0 works``` : origin master code fails version < 3.6
```The change did not work, right, and you had to upgrade to 3.6?``` My change works, I can use this codebase with my very very old version bazel.

**Comment by cpsauer** [comment]
Got it. Do you want to keep using 1.0 for some reason, then? Should we merge in that change?

(If so and you want to get on the contributor list, toss up a PR and I'll accept it! If not, I can just do.)

**Comment by cyy5358** [comment]
Yes, I'm going to use 1.0 due to a project using it 1.0 version for a long long time. My co-workers may not happy with changing bazel version. :thinking:
```Should we merge in that change?```: I use my fork for few hours. It seems work fine. Maybe we could?
 ```If so and you want to get on the contributor list, toss up a PR ```: Yes !!! Love to! My honor.  :laughing::laughing::laughing:
[My PR](https://github.com/hedronvision/bazel-compile-commands-extractor/pull/74)

**Comment by cpsauer** [comment]
Yay! Welcome on board :) It's good to have you. Thanks for leaving things better than you found them.

Happy to take other small fixes that'd help keep you on the mainline.
[But if things get too tricky/involved, I'd strongly recommend you all consider a Bazel upgrade. There's so much that's broken in Bazel 1, and so many new goodies in Bazel 5 and 6!)

Cheers,
Chris
