### ISSUE TITLE
[Windows] Incorrect file path, when path contains spaces (Arm GNU Toolchain)

### ISSUE THREAD

**Issue by johanzwarteveld** [hedronvision/bazel-compile-commands-extractor#81]
When analyzing the generated `compile_commands.json` i noticed broken file paths.
Upon further inspection it seemed that when a `space` was in the path, the file member of the struct was incorrect.

examples:
- `"file": "2021.07\\arm-none-eabi\\include\\machine\\ieeefp.h",` which should have been `"file": "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.07\\arm-none-eabi\\include\\machine\\ieeefp.h",`
- `"file": "embedded\\",` which should have been `"file": "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.07\\...`
- `"file": "c:\\program\\",`
- `"file": "(x86)\\gnu\\",`
- `"file": "arm\\"`
- `"file": "files\\",`
- `"file": "toolchain\\10\\",`

Seems related to the compiler path?
Because `"file": "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\shared\\sdv_driverspecs.h",` is processed as expected.

hedron compile commands used:
```
http_archive(
    name = "hedron_compile_commands",
    url = "https://github.com/hedronvision/bazel-compile-commands-extractor/archive/5ceebcf367f51c6a18fffe726755951a43b50e45.tar.gz",
    strip_prefix = "bazel-compile-commands-extractor-5ceebcf367f51c6a18fffe726755951a43b50e45",
    sha256 = "4deb7cd90ba69983ec7734c0dcc7071828ebdc430a69f82ddbccf698018b9c04",
)
```

**Comment by cpsauer** [comment]
Hey, @johanzwarteveld. Thanks for writing in. That's definitely not the output I want the tool to have. Sorry about the frustration I'm sure this bug has caused.

Here's what I think the problem is--with some assumptions about your setup that I want to check with you.
I'm guessing you're using gcc, or some non cl.exe and non clang-cl.exe compiler on Windows. Is that right?

If not, then I'd love to hear more about your setup or see a snippet of your compile_commands.json so I can see what the command looks like.

If so, then we (and bazel) are asking the compiler to find all the headers used in each source file. The format the compiler uses to dump those dependency lists for non msvc compilers is a .d makefile. And sadly makefiles never really evolved to support paths with spaces, even after all these years. (Usually this is fine; Bazel refuses to run on paths with spaces. But windows implicit include paths with spaces, included via gcc is a case we haven't hit yet.)

Still presuming that's the case, let's see if the compiler does any special, non-standard escaping that we might be able to use to fix this issue. Could I ask you to run a build and look through bazel-out, showing me one of the .d files? That'll let us see how they encode spaces so we can see how to fix.

Thanks!
Chris

**Comment by johanzwarteveld** [comment]
Hasn't been a issue yet. Encountered this when figuring out why CodeCheckers wouldn't accept the compile_commands.json (unrelated issue).

We indeed use [Arm GNU Toolchain](https://developer.arm.com/downloads/-/gnu-rm) for cross-compilation for our embedded targets.

adc_converter.d:
```
bazel-out/x64_windows-fastbuild-ST-01a0c860fa7a/bin/src/components/adc_converter/_objs/adc_converter/adc_converter.o: \
 src/components/adc_converter/src/adc_converter.c \
 src/components/adc_converter/iface/adc_converter.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\lib\gcc\arm-none-eabi\10.3.1\include\stdint.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\stdint.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\machine\_default_types.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\sys\features.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\_newlib_version.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\sys\_intsup.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\sys\_stdint.h \
 src/components/adc_iface/iface/adc_iface.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\lib\gcc\arm-none-eabi\10.3.1\include\stdbool.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\stdlib.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\machine\ieeefp.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\_ansi.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\newlib.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\sys\config.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\lib\gcc\arm-none-eabi\10.3.1\include\stddef.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\sys\reent.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\_ansi.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\sys\_types.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\machine\_types.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\sys\lock.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\sys\cdefs.h \
 c:\program\ files\ (x86)\gnu\ arm\ embedded\ toolchain\10\ 2021.07\arm-none-eabi\include\machine\stdlib.h \
```

adc_converter.o.hedron.compile-commands.headers:
```
["008beb139885221bf675289ee0e5e7b5944c5fd164d4c91fa23cd63215975bcb", ["arm\\", "2021.07\\arm-none-eabi\\include\\newlib.h", "2021.07\\arm-none-eabi\\include\\sys\\_stdint.h", "embedded\\", "src/components/adc_converter/iface/adc_converter.h", "2021.07\\arm-none-eabi\\include\\machine\\_types.h", "c:\\program\\", "2021.07\\arm-none-eabi\\include\\sys\\_intsup.h", "(x86)\\gnu\\", "2021.07\\lib\\gcc\\arm-none-eabi\\10.3.1\\include\\stdbool.h", "2021.07\\arm-none-eabi\\include\\_ansi.h", "2021.07\\arm-none-eabi\\include\\machine\\stdlib.h", "2021.07\\arm-none-eabi\\include\\sys\\cdefs.h", "2021.07\\arm-none-eabi\\include\\_newlib_version.h", "2021.07\\arm-none-eabi\\include\\machine\\_default_types.h", "toolchain\\10\\", "2021.07\\arm-none-eabi\\include\\stdlib.h", "2021.07\\arm-none-eabi\\include\\sys\\reent.h", "2021.07\\lib\\gcc\\arm-none-eabi\\10.3.1\\include\\stddef.h", "files\\", "src/components/adc_iface/iface/adc_iface.h", "2021.07\\arm-none-eabi\\include\\machine\\ieeefp.h", "2021.07\\lib\\gcc\\arm-none-eabi\\10.3.1\\include\\stdint.h", "2021.07\\arm-none-eabi\\include\\sys\\_types.h", "2021.07\\arm-none-eabi\\include\\sys\\features.h", "2021.07\\arm-none-eabi\\include\\stdint.h", "2021.07\\arm-none-eabi\\include\\sys\\config.h", "2021.07\\arm-none-eabi\\include\\sys\\lock.h"]]
```

**Comment by cpsauer** [comment]
Super helpful--looks like they're backslash escaping the spaces.
It's quite late my time, so I've got to crash, but I'll knock out a fix tomorrow.

**Comment by cpsauer** [comment]
BTW, for a code checker, I think there's a good chance you'll want to turn on exclude_headers = "external", and maybe exclude_external_sources = True, depending on the implementation. See the README for more:)

Still, would love it if you'd confirm that the latest change resolves the issue! Thanks again for reporting--and sorry about the bug.

**Comment by cpsauer** [comment]
@johanzwarteveld, checking in on whether this worked for you?

**Comment by johanzwarteveld** [comment]
@cpsauer sorry for the lack of response, i got caught up in work. 
i will check this week.

**Comment by johanzwarteveld** [comment]
@cpsauer fix works as expected thank you very much

**Comment by cpsauer** [comment]
Delighted to hear it! Thanks for following up!
