### ISSUE TITLE
"bazel" not found when running refresh_compile_commands.py

### ISSUE THREAD

**Issue by brtdylan** [hedronvision/bazel-compile-commands-extractor#84]
First off thank you so much for creating this tool!  Being able to use vim+youcompleteme with our bazel build environment has been a long time goal of mine, and this tool makes it all click!

I've got this set up on my machine and now I'm running into an issue setting things up on my colleague's machine.  When running bazel run :refresh_compile_commands, when the rule starts doing the "analyzing commands" section, we get this error `FileNotFoundError: [Errno 2] No such file or directory: 'bazel'`.  It seems like somehow the command `bazel` is unable to be found when this rule is run, whether it's an issue with the PATH, or something else, we can't determine.  Running `bazel version` from within `~/.cache/bazel` manually works, as does trying it within python with `python3 -c import subprocess; subprocess.run(["bazel", "version"])`.  Here's the full output, we're digging into it a bit, but no leads so far so wanted to see if you all had any thoughts? 

```$ bazel run :refresh_compile_commands
INFO: Build options --compilation_mode, --experimental_inmemory_dotd_files, --experimental_inmemory_jdeps_files, and 3 more have changed, discarding analysis cache.
INFO: Analyzed target //:refresh_compile_commands (0 packages loaded, 41221 targets configured).
INFO: Found 1 target...
Target //:refresh_compile_commands up-to-date:
  bazel-bin/refresh_compile_commands.py
  bazel-bin/refresh_compile_commands
INFO: Elapsed time: 4.529s, Critical Path: 0.15s
INFO: 5 processes: 5 internal.
INFO: Build completed successfully, 5 total actions
INFO: Build completed successfully, 5 total actions
>>> Automatically added //external workspace link:
    This link makes it easy for you--and for build tooling--to see the external dependencies you bring in. It also makes your source tree have the same directory structure as the build sandbox.
    It's a win/win: It's easier for you to browse the code you use, and it eliminates whole categories of edge cases for build tooling.
>>> Analyzing commands used in //abc/...
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_user/c51cf94defb6738fca049d2b1bb954fe/execroot/repo/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/repo/refresh_compile_commands.py", line 1038, in <module>
    compile_command_entries.extend(_get_commands(target, flags))
  File "/home/user/.cache/bazel/_bazel_user/c51cf94defb6738fca049d2b1bb954fe/execroot/repo/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/repo/refresh_compile_commands.py", line 880, in _get_commands
    aquery_process = subprocess.run(
  File "/home/user/.cache/bazel/_bazel_user/c51cf94defb6738fca049d2b1bb954fe/external/python3_8_x86_64-unknown-linux-gnu/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/user/.cache/bazel/_bazel_user/c51cf94defb6738fca049d2b1bb954fe/external/python3_8_x86_64-unknown-linux-gnu/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/user/.cache/bazel/_bazel_user/c51cf94defb6738fca049d2b1bb954fe/external/python3_8_x86_64-unknown-linux-gnu/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bazel'

**Comment by brtdylan** [comment]
Actually I think I see the issue.  His machine has bazel installed in his home dir, and bazel commands are not gonna pick up his PATH which contains the local bazel binary...

**Comment by cpsauer** [comment]
Hey, @brtdylan! I'm so glad it's been useful to you guys. Thanks for using the tool and writing in.

I'm glad you were able to help your friend so fast. But I'd like to understand the issue a little better myself, just in case it comes up again or we can make it better somehow. Just to check my understanding: He has it installed in a special directory, which is on his path (and thus invokable as `bazel` from inside the workspace), but then it's then being removed from the path inside bazel run, somehow? (If you guys aren't already using it, I'd highly recommend bazelisk! It's awesome.)

Also, anything I should know about vim/youcompleteme? I'd to add things to the readme to make that easier for people if there are any hard steps.

Cheers,
Chris

**Comment by brtdylan** [comment]
For sure- yes you've got it right.  I'm truly not a bazel expert, but my understanding is it doesn't see a user's environment variables, and I believe he had added to his PATH in his ~/.bashrc to include a local dir with this bazel binary  and so within `bazel run` it no longer had the local bazel dir in PATH.  There may be a way to modify PATH such that bazel run sees it, but I haven't figured that bit out

As for using with youcompleteme, not really!  It's pretty seamless as YCM will read and use a compile_commands.json file if it exists.  I don't think there's any set up required beyond building YCM with the `--clangd-completer` flag.  YCM + this tool are working great together - thank you again!

**Comment by cpsauer** [comment]
Thanks for getting back to me! Both great things to know.

If useful, I'm surprised to hear that bazel run is blocking the environment variables. It's really good to know about the issue in case it comes up again (sounds like you all resolved it some other way). I know it does stop PATH changes when building if you specify [--incompatible_strict_action_env](https://bazel.build/reference/command-line-reference#flag--incompatible_strict_action_env)--which you really should IMO!--but I'm really, really surprised they don't pass through to bazel run. Please do let me know if you learn more here that I should know for helping others.

^ Late update: I was sufficiently bothered by this that I decided to run some tests. At least for me, I'm seeing arbitrary environment variables (PATH included) passed through bazel run, even with `--incompatible_strict_action_env`. Further, I also tested to make sure that the environment variables were correctly getting picked up by subprocesses, which they were. Any other hypotheses about what this might be?

On Vim+YCM, I'm so glad to hear it's been so smooth. I know some others are using it happily, too, but still so great to hear. If there are tweaks that you discover that we should recommend, please to let me know (either here or in a PR or whatever).

Cheers!
Chris

**Comment by brtdylan** [comment]
I made a small py_binary test that just prints the environment variables, and eg for PATH it shows: `'PATH': '/usr/bin:/bin:/usr/local/bin'` which is not what my PATH is externally from bazel.  I also just tried setting a random variable in the shell before running my py_binary with `export ASDF="asdf"` and that didn't show up in my test run so something's happening with the env variables within our bazel environment!

ANDD digging into this some more, it looks like our repo has a script wrapper that /usr/bin/bazel calls which is manually setting all the environment variables 🙃. it looks like this is our take on something like bazelisk, which is specifying the bazel version and sandboxing it a bit more.

SO crisis averted, all is right with the world and I learned properly why I can't use env vars within our bazel sandbox.  Thank you for digging into this with me, I'll definitely let y'all know if anything comes up!

**Comment by cpsauer** [comment]
Way to trace it down! Thanks for being so great to work with :)

**Comment by brtdylan** [comment]
Hey there - I ran into one wrinkle today that I thought could be useful feedback for the project.  It's not an issue, more of a comment, but we are using gazelle and when it's run after running this tool, it will dive into the created `external/` symlink and muck around with BUILD files it shouldn't have permission to touch.  Fixed by excluding it for gazelle with `# gazelle:exclude external` in the root BUILD.bazel file

**Comment by cpsauer** [comment]
Ooh, @brtdylan, thanks for flagging this. Good eye.

Gazelle should really just automatically ignore all symlinks that point into bazel's output.
So I [tossed up a quick PR to try to fix the underlying issue](https://github.com/bazelbuild/bazel-gazelle/pull/1384).
Could I ask you to give it a quick peek/test and let me know what you think? 

Until it's merged, I'll put a note about your good workaround in the readme.

BTW, I like your seal profile photo :)

**Comment by cpsauer** [comment]
That'd be great! Thanks for engaging back--and for a great workaround in the meantime. I'm sure it's helped a bunch of people since.

**Comment by cpsauer** [comment]
Hi, Pär! Sure is. Any chance you've got a similar set of environment-setting wrappers that are setting the Bazel path to exclude that new install location on Apple Silicon?

(I'm medium-sure this isn't an issue with default Bazel--I'm typing this from an Apple Silicon machine and can't haven't managed to repro with various combinations of bazel rolling, latest, and with and without the `--incompatible_strict_action_env` and `--action_env=PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:.` flags. Probably there's a flag or other custom config that causes this that I don't know about. I wish I knew the answer for you, but only you know your config. Can you try to track down what configuration causes this and report back so we can solve it for everyone? )

**Comment by parbo** [comment]
We have `build --incompatible_strict_action_env` in our `.bazelrc` which is probably the [reason](https://bazel.build/reference/command-line-reference#flag--incompatible_strict_action_env). 

We do have a wrapper script that also sets the paths, but I wasn't using that.

**Comment by parbo** [comment]
Well, apparently bazel will invoke a wrapper script called `tools/bazel` if it exists. So I was using the wrapper script after all.

**Comment by cpsauer** [comment]
Ah, got it. To conclude, then, not  `--incompatible_strict_action_env`, since that's only for actions, but instead PATH being set for everything, including `bazel run` via the wrapper script?

**Comment by parbo** [comment]
Apparently, yes.
