### ISSUE TITLE
32k CreateProcessW problem on Windows

### ISSUE THREAD

**Issue by Warchant** [hedronvision/bazel-compile-commands-extractor#88]
[At this point](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/refresh.template.py#L227-L232) we want to re-generate .d files to get a list of header dependencies from them. 

On windows [there's a limit of 2**15 chars](https://devblogs.microsoft.com/oldnewthing/20031210-00/?p=41553#:~:text=The%20maximum%20command%20line%20length,comes%20from%20the%20UNICODE_STRING%20structure.) per single CreateProcessW WinAPI call. This means that this line can throw `FileNotFoundError: [WinError 206] The filename or extension is too long` in case if all args combined are longer than 32k. 

A workaround is to create an "args file" with 1 line per flag and run it like this: 
```bash
echo --arg1 >> args.txt
echo --arg2 >> args.txt
gcc @args.txt
```
This is actually done by bazel automatically when you enable `compiler_param_file` feature.

To trigger 32k-chars exception on windows:
```python
>>> import subprocess
>>> subprocess.run(["gcc"] + ["abc"] *32000)
FileNotFoundError: [WinError 206] The filename or extension is too long
```

This GH issue is a request to support "args file" for all "compiler invocations" from the tool.

**Comment by cpsauer** [comment]
Hey, @Warchant! Thanks for using the tool and writing in.

Good eye. We do this for msvc/clangcl, but I forgot to do it for gcc/clang on Windows. I'll generalize the code.

[We have to turn off the compiler_param_file when introspecting bazel. Otherwise, it gives us lots of references to param files that don't exist before a full build, so we can't get the arguments to clangd.]

Also, man, I saw your location is listed as Kharkiv. My heart goes out to you guys. I'm curious what life is like--and impressed that you're still able to interact on GitHub.

Cheers,
Chris

**Comment by cpsauer** [comment]
Had some dinner and then pushed up a commit that should fix. I'd love it if you'd take a look and give it a try, making sure things look good and are fixed for you.

**Comment by Warchant** [comment]
Thank you for great tool and fast response :) 

>Also, man, I saw your location is listed as Kharkiv. My heart goes out to you guys. I'm curious what life is like--and impressed that you're still able to interact on GitHub.

Thank you for support. When you live in Kharkiv during the war, you ocasionally hear (and feel) explosions from singular rocket, shells or multiple explosions from cluster munitions. It was rare day when you didn't hear any of them. And it was like this for 6 months, every day, until our army liberated Kharkiv region in September. I recall a number of 150k people who lost their homes in Kharkiv city (as per mayor), it is like every 10-th. Russians only use rockets now (Iskander and C300, maybe something else), as the distance does not allow them to use artillery anymore, so it became a lot "better".

After Ua success Ru started to strike power plants and energy infrastructure. Today I didn't have electricity all day because of a recent strike ¯\\\_(ツ)\_/¯

They strike civilian infrastructure to make ukrainians go to concessions - they want to freeze the war , to stop our counteroffensive, prepare, then finish with what they started. But it won't happen. Ukraine will liberate all captured territories, and terrorist Ru regime will fall.
