### ISSUE TITLE
Improve support of proprietary compilers

### ISSUE THREAD

**Issue by Warchant** [hedronvision/bazel-compile-commands-extractor#90]
This tool does not work with proprietary compilers which do not have gcc-compatible CLI interface. For now I made my private fork with "hardcoded" types of fixes. In this issue I will enumerate my changes:

1. [Here](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/refresh.template.py#L476-L479), `-o` or `/Fo` are expected. But one of compilers I tried uses `--output_file=something/file.o`. Other `-fe something/file.o`. Maybe potential solution is to give users ability to define `output_flag="-o"` value in bazel rule, then use it to search for output flag? 
2. [Here](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/refresh.template.py#L519) because of "else" condition, all proprietary compilers try to run `_get_headers_gcc` and will obviously fail, because they won't have gcc-compatible flags. I excluded this call during my tests, not sure why it is required.
3. [Here](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/refresh.template.py#L564-L568) you utilize some bazel internals to get the filename. More portable solution is to search for an argument which `arg.endswith(_get_files.source_extensions)`. If this returns 1 candidate, then we found a file. Else, fallback to current approach, or fail.
4. [Here](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/refresh.template.py#L809) comment says that you output one entry per header. And I see `_get_headers_gcc` is necessary just to get a list of headers for this deduplication. In my solution I check entries for uniqueness [here](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/refresh.template.py#L1043) by primary key (directory, file). It does not require additional .d file generation and parsing, so it eliminates the need for `_get_headers_gcc`. It could be that I misunderstood the purpose of `_get_headers_gcc`...

With these points fixed and with support of #88, the tool works for multiple proprietary compilers.

**Comment by Warchant** [comment]
>I'd like to understand a bit better about what you're aiming to do here, one step up the backtrace of your goals. 

My goal is to just generate compile_commands.json, without an intention of running clangd on it. 
It is needed for other tools, which can process custom compilers.

**Comment by cpsauer** [comment]
Got it! Thanks. Can't say I've used most of those, so I extra appreciate your linking me to them.

Bummer that they aren't (all) flag compatible with MSVC/gcc. If they were close, I'd propose that we add code to massage their flags to be clang compatible so you could run those tools, but it sounds like there are too many and/or the clang tools aren't enough of a goal?

**Comment by cpsauer** [comment]
I'm guessing you don't need compile commands entries for headers for the static analysis tool?

If that's right, then I'd propose we resolve this as follows, so we can get you everything you want while keeping you on the mainline and continue to collaborate and get you future fixes:
- You set `exclude_headers = "all"` in your configuration. That'll turn off the header extraction you don't want, make things run fast, and bypass most of the coupling with gcc/clang.
- And then if we can come up with a more general codepath for (3) that works in more cases, that'd get things working for you. The best one I can think of right now would be filter args for ending with a source extension like you propose, plus eliminating those where the arg starts with a - or is a directory (with caching bc it's easy and will probably make a performance difference). Would you be down to PR that, and we'll get you on the contributor board and merged back in? Obviously, if you think of something even more robust/better, I'm all for it.

**Comment by cpsauer** [comment]
@Warchant, please do let me know what you think of that approach when you get a chance!
(I know you've got, *ahem*, a lot going on around you, so no pressure--just thought of you while I was tweaking my fix to your other issue.)

**Comment by cpsauer** [comment]
Hey @Warchant--haven't heard from you in a while. I'm hoping you're OK!

I was about to implement the workaround for (3) that I'd proposed above, but the directory check isn't actually sufficient, since the arg with a source extension can be generated directory and therefore not yet exist. Indeed that's exactly the example in #37. My bad.

So I've implemented exactly your original suggestion. Hopefully that plus `exclude_headers = "all"` gets this working for your use case. If you want the clang tools to work, the next step would be to add _platform_patch functions for your compilers, massaging their flags into clang compatible ones that the tooling can understand. 

I'm going to close this for now, since I haven't heard from you in a good while, but I can open this right back up if you reply and want it.
