### ISSUE TITLE
Crash AttributeError: 'types.SimpleNamespace' object has no attribute 'targets'

### ISSUE THREAD

**Issue by alexander-born** [hedronvision/bazel-compile-commands-extractor#92]
Hey, 

great tool <3
wanted to report a crash for a header only library.

It only fails when using  `exclude_external_sources` or `exclude_headers == "external"`

```
  File "/home/user/.cache/bazel/_bazel_user/1ccf5f150b64de76858888618e3183bd/execroot/ddad/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/ddad/refresh_compile_commands.py", line 795, in _convert_compile_commands                               
    targets_by_id = {target.id : target.label for target in aquery_output.targets}                                                                                                                                                                                    
AttributeError: 'types.SimpleNamespace' object has no attribute 'targets'
```

**Comment by cpsauer** [comment]
Hey! Good to hear form you again, Alexander. Thanks--and thanks for reporting.

To get commands for a header-only library you'll need to instead specify a test or binary target that compiles it (search "header-only" in README.md)--but you may already know that. 

I've changed the code to issue a warning to that effect and continue on (rather than crashing).

Could I ask you to check the latest for me, just to make sure that it resolves this crash?

Thanks again for reporting and for using this tool!
Chris

**Comment by alexander-born** [comment]
Yeah, thanks Christoph. 

I have a shortcut which runs this tool for the target of the current file I'm in. That's why I happened to start it for a header only library.

I only use this shortcut, when I am new parts of the codebases which I don't have the compile commands for.

**Comment by cpsauer** [comment]
Ooh, interesting! Could I ask you to tell me a bit more about what you're up to with the shortcut?
(Understanding what you're using this for helps me better sculpt it to match needs.)

(Some hypotheses in my head, which may or may not be right: Perhaps this is about new parts of the codebase, not yet linked into the main build graph? Or maybe it's about about speed, things being too slow to run over the whole build target?)

**Comment by alexander-born** [comment]
Basically just convenience for me, as I had all the necessary building blocks anyways.

In my work repos this tool is not integrated (don't ask why...), so I wrote a little bash function
```bash
refresh_compile_commands <target> <additional_flags>
```
This clones/pulls this repo, patches my work repo's WORKSPACE and BUILD file with the necessary setup, runs this tool and cleans up the modifications it did.

Also I am using neovim and wrote a bazel plugin. There
is a [method] (https://github.com/alexander-born/bazel-vim/blob/10731a0571723ce388ee75e1730ea27cca5a41f7/plugin/bazel_vim.py#L61) to get the target of the current file, which is needed for building/ running debugging tests.

These combined give me the shortcut to run this tool for the target of the current file I'm in.

Normally I run `refresh_compile_commands` for //application/foo/... which is sufficient 99% of the time. 

But sometimes I need the compile commands for a single specific target, because some targets use linktime polymorphism and clangd would otherwise have multiple implementations it can jump to. 

Or the rare case I want compile commands outside of //application/foo/...
